# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Test on ubuntu-latest with ${{ matrix.dltool }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dltool: ['curl', 'wget']

    steps:
    - uses: actions/checkout@v1
    - name: Use ${{ matrix.dltool }}
      run: |
        bash test/test_${{ matrix.dltool }}.sh
